services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-${COMPOSE_PROJECT_NAME:-vibetuner}}
      MONGO_USER: ${MONGO_USER:-}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-}
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_USER: ${REDIS_USER:-}
      REDIS_DATABASE: ${REDIS_DATABASE:-0}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  app:
    build:
      context: .
      args:
        VERSION: ${VERSION:-0.0.0}
        PYTHON_VERSION: ${PYTHON_VERSION}
        ENVIRONMENT: ${ENVIRONMENT:-development}
    image: ${COMPOSE_PROJECT_NAME}:dev
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/ping')",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    ports:
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

volumes:
  mongo_data:
  redis_data:
# Above this line, nothing should be changed
# End of file: do not remove this line or add any content below
