services:
  mongo:
    image: mongo:8.2
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  app:
    build:
      context: .
      args:
        VERSION: ${VERSION:-0.0.0}
        PYTHON_VERSION: ${PYTHON_VERSION}
        ENVIRONMENT: ${ENVIRONMENT:-development}
    image: ${COMPOSE_PROJECT_NAME}:dev
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/ping')",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    ports:
      - "8000:8000"
    #    env_file:
    #      - .env
    environment:
      #    mongodb_url: MongoDsn | None = None
      #    redis_url: RedisDsn | None = None
      - DEBUG=true
      - MONGODB_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

volumes:
  mongo_data:
  redis_data:
# Above this line, nothing should be changed
# End of file: do not remove this line or add any content below
