_default:
    @just --list

import '.justfiles/helpers.justfile'
import '.justfiles/localdev.justfile'
import '.justfiles/cicd.justfile'
import '.justfiles/i18n.justfile'
import '.justfiles/linting.justfile'
import '.justfiles/formatting.justfile'
import '.justfiles/scaffolding.justfile'

# Run all linting checks
[group('linting')]
lint: type-check lint-md lint-py lint-toml lint-jinja
